### PR TITLE
Fallback. Added support for not shared openssl.

### PR DESCRIPTION
**Pull request by merqlove**
Subject.

### CODE REVIEW

**Comment by mal** [comment]
You should be able to fix that failing test suite by changing [these two lines](https://github.com/mal/forsake/blob/master/appveyor.yml#L14-L15) to use `Win32OpenSSL-1_0_2f.exe`.

Also please can you be more specific about which support this is adding? `0.6` is ancient and there are people in my office already using this lib sucessfully on OSX.

**Comment by merqlove** [comment]
Hi,
About support, look into var’s comment in gypfile.
OS X 10.11+ don’t have openssl headers anymore.

## 

Best regards,
Alexander Merkulov

**Comment by mal** [comment]
Great, thanks. I'll try and get this released early next week. :+1:

**Comment by mal** [comment]
Wow, very sorry this slipped through the cracks. :anguished:

**Pull request merged**
